name: pdfarranger
base: core22
adopt-info: pdfarranger
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
environment:
   PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
   
slots:
  pdfarranger:
    interface: dbus
    bus: session
    name: com.github.jeromerobert.pdfarranger

apps:
  pdfarranger:
    command: bin/pdfarranger
    extensions: [gnome]
    environment:
      LD_LIBRARY_PATH: $SNAP/lib/python3.10/site-packages
    plugs:
      - home
      - raw-usb
      - network
      - network-status
      - optical-drive
      - removable-media
    common-id: com.github.jeromerobert.pdfarranger
    desktop: share/applications/com.github.jeromerobert.pdfarranger.desktop
   
   
parts:
  pdfarranger:
    source: https://github.com/pdfarranger/pdfarranger.git
    plugin: python
    parse-info: [share/metainfo/com.github.jeromerobert.pdfarranger.metainfo.xml]
    python-packages:
      - distutils-extra-python==2.39.2
    build-packages:
      - python3-pip
      - python3-distutils-extra
      - python3-wheel
      - python3-gi
      - img2pdf
      - python3-img2pdf
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - gir1.2-poppler-0.18
      - gir1.2-handy-1
      - python3-setuptools
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0) 
    
   
   
  
